sudo: required

services:
  - docker

language: generic

script:
  - if [ "$TRAVIS_BRANCH" == "main" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build . -t giusedroid/ffmpeg-lgpl:amazonlinux2;
    docker push giusedroid/ffmpeg-lgpl:amazonlinux2;
    fi